name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ fromJson(matrix.target).rid }}

    strategy:
      fail-fast: false

      matrix:
        target:
          - '{"goos":"windows","rid":"win-x64","os":"windows-2022"}'
          - '{"goos":"linux","rid":"linux-x64","os":"ubuntu-20.04"}'
          - '{"goos":"darwin","rid":"osx-x64","os":"macos-11"}'

    runs-on: ${{ fromJson(matrix.target).os }}

    env:
      GOOS: ${{ fromJson(matrix.target).goos }}
      GOARCH: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Cache Build Caches
        uses: actions/cache@v3
        with:
          path: build/caches/
          key: koi-${{ runner.os }}-${{ hashFiles('config.ts') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
          cache: true
          cache-dependency-path: config.ts

      - name: Install Build Package
        run: |
          yarn install --frozen-lockfile
        shell: bash

      - name: Lint
        run: |
          yarn gulp ciLint
        shell: bash
